# Generated by Django 4.2.5 on 2024-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('Tipo_De_trabalho', models.CharField(max_length=100, verbose_name='Tipo de trabalho')),
                ('quantidade', models.CharField(max_length=100, verbose_name='quantidade')),
                ('valor_trabalho', models.CharField(max_length=100)),
                ('valor_pago', models.CharField(max_length=100, null=True)),
                ('metodo_de_pagamento', models.CharField(max_length=100, null=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.CharField(max_length=800, verbose_name='Descrição do trabalho')),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PRODUTOS',
            },
        ),
    ]
