# Generated by Django 4.2 on 2023-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('Tipo_De_trabalho', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=100)),
                ('valor_trabalho', models.CharField(max_length=100)),
                ('valor_pago', models.CharField(max_length=100, null=True)),
                ('sinal', models.CharField(editable=False, max_length=100, verbose_name='Proporção')),
                ('metodo_de_pagamento', models.CharField(max_length=100, null=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.CharField(max_length=800, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído'), ('Entregue', 'Entregue')], default='Pendente', max_length=100)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PRODUTOS',
            },
        ),
    ]
