# Generated by Django 4.2 on 2023-07-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sinal',
            field=models.CharField(choices=[('0%', '0%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], editable=False, max_length=100, verbose_name='Proporção'),
        ),
    ]
