# Generated by Django 4.2.5 on 2024-01-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sinal',
            field=models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default=1, editable=False, max_length=100, verbose_name='Proporção'),
            preserve_default=False,
        ),
    ]
