# Generated by Django 4.2.5 on 2024-01-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tipo_de_trabalho',
            new_name='Tipo_De_trabalho',
        ),
    ]
