# Generated by Django 4.2.5 on 2024-01-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_tipo_de_trabalho_product_tipo_de_trabalho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Tipo_De_trabalho',
            new_name='tipo_de_trabalho',
        ),
        migrations.RemoveField(
            model_name='product',
            name='valor_pago',
        ),
    ]
