# Generated by Django 4.2.5 on 2024-01-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_tipo_de_trabalho_product_tipo_de_trabalho_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTotal',
        ),
    ]
